In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("/home/frizzyzy/Downloads/houseprice.csv", usecols=["SalePrice", "MSSubClass", "MSZoning", "LotFrontage", "LotArea", "Street", "YearBuilt", "LotShape", "1stFlrSF", "2ndFlrSF"]).dropna()

In [3]:
df.shape

(1201, 10)

In [4]:
df.head()

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  YearBuilt  \
0          60       RL         65.0     8450   Pave      Reg       2003   
1          20       RL         80.0     9600   Pave      Reg       1976   
2          60       RL         68.0    11250   Pave      IR1       2001   
3          70       RL         60.0     9550   Pave      IR1       1915   
4          60       RL         84.0    14260   Pave      IR1       2000   

   1stFlrSF  2ndFlrSF  SalePrice  
0       856       854     208500  
1      1262         0     181500  
2       920       866     223500  
3       961       756     140000  
4      1145      1053     250000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1201 entries, 0 to 1459
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MSSubClass   1201 non-null   int64  
 1   MSZoning     1201 non-null   object 
 2   LotFrontage  1201 non-null   float64
 3   LotArea      1201 non-null   int64  
 4   Street       1201 non-null   object 
 5   LotShape     1201 non-null   object 
 6   YearBuilt    1201 non-null   int64  
 7   1stFlrSF     1201 non-null   int64  
 8   2ndFlrSF     1201 non-null   int64  
 9   SalePrice    1201 non-null   int64  
dtypes: float64(1), int64(6), object(3)
memory usage: 103.2+ KB


In [6]:
for i in df.columns:
    print(f"Column name {i} and unique values are {len(df[i].unique())}")

Column name MSSubClass and unique values are 15
Column name MSZoning and unique values are 5
Column name LotFrontage and unique values are 110
Column name LotArea and unique values are 869
Column name Street and unique values are 2
Column name LotShape and unique values are 4
Column name YearBuilt and unique values are 112
Column name 1stFlrSF and unique values are 678
Column name 2ndFlrSF and unique values are 368
Column name SalePrice and unique values are 597


In [7]:
import datetime
datetime.datetime.now().year

2023

In [8]:
df['Total years']=datetime.datetime.now().year-df['YearBuilt']

In [9]:
df.drop("YearBuilt", axis=1, inplace=True)

In [10]:
df.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', '1stFlrSF', '2ndFlrSF', 'SalePrice', 'Total years'],
      dtype='object')

In [11]:
df.head()

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  1stFlrSF  \
0          60       RL         65.0     8450   Pave      Reg       856   
1          20       RL         80.0     9600   Pave      Reg      1262   
2          60       RL         68.0    11250   Pave      IR1       920   
3          70       RL         60.0     9550   Pave      IR1       961   
4          60       RL         84.0    14260   Pave      IR1      1145   

   2ndFlrSF  SalePrice  Total years  
0       854     208500           20  
1         0     181500           47  
2       866     223500           22  
3       756     140000          108  
4      1053     250000           23

In [12]:
#creating categorical features for classfications with less number of variations
cat_features=['MSSubClass', 'MSZoning', 'Street', 'LotShape']
out_feature='SalePrice'

In [13]:
#to convert the numerical values to categorical features, we use LabelEncoder
#labelencoder provides a way of ranking here
#Label encoding used in place of one hot encoding because we will further apply embedding layers by assigning unique index 

from sklearn.preprocessing import LabelEncoder

# lbl_encoders={}
# lbl_encoders['MSSubClass']=LabelEncoder()
# lbl_encoders["MSSubClass"].fit_transform(df["MSSubClass"])



#example applied to MSSubClass

In [14]:
#applying label encoding to all categorical features
label_encoders={}
for i in range(len(cat_features)):
    label_encoders[cat_features[i]]=LabelEncoder()
    df[cat_features[i]]=label_encoders[cat_features[i]].fit_transform(df[cat_features[i]])

In [15]:
df

MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  1stFlrSF  \
0              5         3         65.0     8450       1         3       856   
1              0         3         80.0     9600       1         3      1262   
2              5         3         68.0    11250       1         0       920   
3              6         3         60.0     9550       1         0       961   
4              5         3         84.0    14260       1         0      1145   
...          ...       ...          ...      ...     ...       ...       ...   
1455           5         3         62.0     7917       1         3       953   
1456           0         3         85.0    13175       1         3      2073   
1457           6         3         66.0     9042       1         3      1188   
1458           0         3         68.0     9717       1         3      1078   
1459           0         3         75.0     9937       1         3      1256   

      2ndFlrSF  SalePrice  Total years  
0          854     208500           20  
1            0     181500           47  
2          866     223500           22  
3          756     140000          108  
4         1053     250000           23  
...        ...        ...          ...  
1455       694     175000           24  
1456         0     210000           45  
1457      1152     266500           82  
1458         0     142125           73  
1459         0     147500           58  

[1201 rows x 10 columns]

In [16]:
cat_features=np.stack([df['MSSubClass'], df['MSZoning'], df['Street'], df['LotShape']],1)
cat_features


array([[5, 3, 1, 3],
       [0, 3, 1, 3],
       [5, 3, 1, 0],
       ...,
       [6, 3, 1, 3],
       [0, 3, 1, 3],
       [0, 3, 1, 3]])

In [17]:
continuous_features=[]
for i in df.columns:
    if i in['MSSubClass', 'MSZoning', 'Street', 'LotShape', 'SalePrice']:
        pass
    else:
        continuous_features.append(i)

continuous_features

['LotFrontage', 'LotArea', '1stFlrSF', '2ndFlrSF', 'Total years']

In [18]:
import torch

In [19]:
# Now we use pytorch to actually stack the continuous varibles to a tensor
continuous_values=np.stack([df[i].values for i in continuous_features], axis=1)
cont_values=torch.tensor(continuous_values, dtype=torch.float)

#int cannot be used tfor continuous values

In [20]:
continuous_values.dtype

dtype('float64')

In [21]:
#converting target/ SalePrice to tensors as well

y=torch.tensor(df['SalePrice'].values, dtype=torch.float).reshape(-1,1)
y
#reshaping done to prevent one dim array formation

tensor([[208500.],
        [181500.],
        [223500.],
        ...,
        [266500.],
        [142125.],
        [147500.]])

In [22]:
print(df.shape)
cat_features.shape, continuous_values.shape, y.shape

#this is a good practice to proofread whether the dataset prepared is correct ot not

(1201, 10)


((1201, 4), (1201, 5), torch.Size([1201, 1]))

In [23]:
#embedding for categorical features

cat_dims=[len(df[cols].unique()) for cols in ["MSSubClass", "MSZoning", "Street", "LotShape"]]


#embedding output dimensions, for rule refer to fast.ai 
embedding_dim=[(x, min(50, (x+1)//2)) for x in cat_dims]
embedding_dim

##data pre processing steps until here

[(15, 8), (5, 3), (2, 1), (4, 2)]

In [24]:
import torch.nn as nn
import torch.nn.functional as F
embed_representation=nn.ModuleList([nn.Embedding(inp,out) for inp,out in embedding_dim])
embed_representation

ModuleList(
  (0): Embedding(15, 8)
  (1): Embedding(5, 3)
  (2): Embedding(2, 1)
  (3): Embedding(4, 2)
)

In [25]:
cat_features=torch.tensor(cat_features, dtype=torch.int)

cat_featuresz=cat_features[:4]
cat_featuresz

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        [6, 3, 1, 0]], dtype=torch.int32)

In [26]:
cat_features

#column wise output for each categorical feature

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        ...,
        [6, 3, 1, 3],
        [0, 3, 1, 3],
        [0, 3, 1, 3]], dtype=torch.int32)

In [27]:
#now we have to convert it into embedding vectors

pd.set_option('display.max_rows', 500)
embedding_val=[]

for i,e in enumerate(embed_representation):
    embedding_val.append(e(cat_features[:,i]))

#passing whole column records for converting to vectors

In [28]:
embedding_val

#the first feature is represented by 8 dimensions, the second by 8 dimesions and so forth for the values of the first column
#since from the dimensions 15 as input and 8 as output

[tensor([[-1.2513, -0.2544,  0.4364,  ..., -1.8865,  0.0282,  0.8068],
         [ 1.8036,  0.3069, -0.7143,  ...,  0.7770, -0.4858,  1.3633],
         [-1.2513, -0.2544,  0.4364,  ..., -1.8865,  0.0282,  0.8068],
         ...,
         [ 0.2922,  3.3085, -0.4740,  ...,  0.4278, -1.0475,  0.0230],
         [ 1.8036,  0.3069, -0.7143,  ...,  0.7770, -0.4858,  1.3633],
         [ 1.8036,  0.3069, -0.7143,  ...,  0.7770, -0.4858,  1.3633]],
        grad_fn=<EmbeddingBackward0>),
 tensor([[-0.1652, -0.0255,  0.9296],
         [-0.1652, -0.0255,  0.9296],
         [-0.1652, -0.0255,  0.9296],
         ...,
         [-0.1652, -0.0255,  0.9296],
         [-0.1652, -0.0255,  0.9296],
         [-0.1652, -0.0255,  0.9296]], grad_fn=<EmbeddingBackward0>),
 tensor([[-0.7709],
         [-0.7709],
         [-0.7709],
         ...,
         [-0.7709],
         [-0.7709],
         [-0.7709]], grad_fn=<EmbeddingBackward0>),
 tensor([[ 0.3944, -1.2331],
         [ 0.3944, -1.2331],
         [ 0.6964, -0.

In [29]:
cat_featuresz

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        [6, 3, 1, 0]], dtype=torch.int32)

In [30]:
embedding_val

[tensor([[-1.2513, -0.2544,  0.4364,  ..., -1.8865,  0.0282,  0.8068],
         [ 1.8036,  0.3069, -0.7143,  ...,  0.7770, -0.4858,  1.3633],
         [-1.2513, -0.2544,  0.4364,  ..., -1.8865,  0.0282,  0.8068],
         ...,
         [ 0.2922,  3.3085, -0.4740,  ...,  0.4278, -1.0475,  0.0230],
         [ 1.8036,  0.3069, -0.7143,  ...,  0.7770, -0.4858,  1.3633],
         [ 1.8036,  0.3069, -0.7143,  ...,  0.7770, -0.4858,  1.3633]],
        grad_fn=<EmbeddingBackward0>),
 tensor([[-0.1652, -0.0255,  0.9296],
         [-0.1652, -0.0255,  0.9296],
         [-0.1652, -0.0255,  0.9296],
         ...,
         [-0.1652, -0.0255,  0.9296],
         [-0.1652, -0.0255,  0.9296],
         [-0.1652, -0.0255,  0.9296]], grad_fn=<EmbeddingBackward0>),
 tensor([[-0.7709],
         [-0.7709],
         [-0.7709],
         ...,
         [-0.7709],
         [-0.7709],
         [-0.7709]], grad_fn=<EmbeddingBackward0>),
 tensor([[ 0.3944, -1.2331],
         [ 0.3944, -1.2331],
         [ 0.6964, -0.

In [31]:
#the stacking for embedded values is still improper
z=torch.cat(embedding_val, axis=1)
z

#values are appended to the end of each row for the tensors, actually similar to the stacking in numpy but pytorch provides functionality directly

tensor([[-1.2513, -0.2544,  0.4364,  ..., -0.7709,  0.3944, -1.2331],
        [ 1.8036,  0.3069, -0.7143,  ..., -0.7709,  0.3944, -1.2331],
        [-1.2513, -0.2544,  0.4364,  ..., -0.7709,  0.6964, -0.0201],
        ...,
        [ 0.2922,  3.3085, -0.4740,  ..., -0.7709,  0.3944, -1.2331],
        [ 1.8036,  0.3069, -0.7143,  ..., -0.7709,  0.3944, -1.2331],
        [ 1.8036,  0.3069, -0.7143,  ..., -0.7709,  0.3944, -1.2331]],
       grad_fn=<CatBackward0>)

In [32]:
dropout=nn.Dropout(0.4)

final_embed=dropout(z)
#used to prevent the neurons from overfitting
#using dropout prevents all the neurons in a layer from synchronously optimizing their weights

In [33]:
help(pd.get_dummies)

Help on function get_dummies in module pandas.core.reshape.encoding:

get_dummies(data, prefix=None, prefix_sep: 'str | Iterable[str] | dict[str, str]' = '_', dummy_na: 'bool' = False, columns=None, sparse: 'bool' = False, drop_first: 'bool' = False, dtype: 'NpDtype | None' = None) -> 'DataFrame'
    Convert categorical variable into dummy/indicator variables.
    
    Each variable is converted in as many 0/1 variables as there are different
    values. Columns in the output are each named after a value; if the input is
    a DataFrame, the name of the original variable is prepended to the value.
    
    Parameters
    ----------
    data : array-like, Series, or DataFrame
        Data of which to get dummy indicators.
    prefix : str, list of str, or dict of str, default None
        String to append DataFrame column names.
        Pass a list with length equal to the number of columns
        when calling get_dummies on a DataFrame. Alternatively, `prefix`
        can be a diction

In [34]:
#define a class for a neural network
#nn.Module is required to inherit to create sequential neural networks

import torch
import torch.nn as nn
import torch.nn.functional as F

class FeedForward(nn.Module):
    def __init__(self, embedding_dim, n_cont, out_sz, layers, p):
        super().__init__()
        self.embeds=nn.ModuleList([nn.Embedding(inp,out) for inp,out in embedding_dim])
        self.emb_drop=nn.Dropout(p)
        self.bn_count=nn.BatchNorm1d(n_cont)
        #batch normalizaiton for continuos variables only

        
        layerlist=[]
        n_emb=sum((out for inp,out in embedding_dim))
        n_in=n_emb+n_cont

        #total output from embedding features and total inputs from continuous features

        for i in layers:
            layerlist.append(nn.Linear(n_in,i))
            layerlist.append(nn.ReLU(inplace=True))
            layerlist.append(nn.BatchNorm1d(i))
            layerlist.append(nn.Dropout(p))

            n_in=i

        layerlist.append(nn.Linear(layers[-1], out_sz))

        #wrapping all the layers' list now into sequantial layer
        self.layers=nn.Sequential(*layerlist)

    def forward(self, x_cat, x_cont):
        embeddings=[]

        #creating the embeddings

        for i,e in enumerate(self.embeds):
            embeddings.append(e(x_cat[:,i]))
        #concatenating the embeddings
        #then applying a dropout layer
        x=torch.cat(embeddings, 1)
        x=self.emb_drop(x)

        x_cont=self.bn_count(x_cont)
        #now concatenating all the input as well as continuous features
        x=torch.cat([x,x_cont], 1)
        x=self.layers(x)
        return x

In [35]:
len(continuous_features)

5

In [36]:
torch.manual_seed(1000)
model=FeedForward(embedding_dim, len(continuous_features), 1, [100, 50],p=0.4)

#initializing two layers with 100 neurons and 50 neurons respectively

In [37]:
model

FeedForward(
  (embeds): ModuleList(
    (0): Embedding(15, 8)
    (1): Embedding(5, 3)
    (2): Embedding(2, 1)
    (3): Embedding(4, 2)
  )
  (emb_drop): Dropout(p=0.4, inplace=False)
  (bn_count): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layers): Sequential(
    (0): Linear(in_features=19, out_features=100, bias=True)
    (1): ReLU(inplace=True)
    (2): BatchNorm1d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): Dropout(p=0.4, inplace=False)
    (4): Linear(in_features=100, out_features=50, bias=True)
    (5): ReLU(inplace=True)
    (6): BatchNorm1d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (7): Dropout(p=0.4, inplace=False)
    (8): Linear(in_features=50, out_features=1, bias=True)
  )
)

In [38]:
loss=nn.MSELoss()

optimizer=torch.optim.Adam(model.parameters(),lr=0.01)


In [39]:
df.shape

(1201, 10)

In [40]:
cont_values.shape

torch.Size([1201, 5])

In [41]:
#performing a train test split on the dataset
#usual train_test_split from sklearn.model_selection does not work because here we have tensors unlike values in a usual dataset

batch_size=1200
test_size=int(batch_size *0.15)
train_categorical=cat_features[:batch_size - test_size]
test_categorical=cat_features[batch_size-test_size: batch_size]
train_cont=cont_values[:batch_size - test_size]
test_cont=cont_values[batch_size - test_size:batch_size]

y_train=y[:batch_size - test_size]
y_test=y[batch_size-test_size: batch_size]



In [42]:
len(train_categorical), len(test_categorical), len(train_cont), len(test_cont)

(1020, 180, 1020, 180)

In [43]:
epochs=5000
final_losses=[]
for i in range(epochs):
    i+=1
    y_pred=model(train_categorical, train_cont)
    losses=torch.sqrt(loss(y_pred, y_train))
    final_losses.append(losses)

    if i%1000==0:
        print(f"Epoch number{i} and loss is {losses.item()}")
    optimizer.zero_grad()
    losses.backward()
    optimizer.step()
    

Epoch number1000 and loss is 184412.625


In [ ]:
import matplotlib.pyplot as plt

plt.plot(range(epochs), final_losses)
plt.xlabel('number of epochs')
plt.ylabel('RMSE loss')

NameError: name 'epochs' is not defined

In [1]:
y_pred=""
with torch.no_grad():
    y_pred=model(test_categorical, test_cont)
    loss=torch.sqrt(y_pred, y_test)

print(f"Rmse{losses}")

NameError: name 'torch' is not defined

In [2]:
data_verify=pd.DataFrame(y_test.tolist(), columns=['actual data'])
data_predicted=pd.DataFrame(y_pred.tolist(), columns=['predicted data'])
final_output=pd.concat([data_verify, data_predicted], axis=1)
final_output['Difference']=final_output['actual data']-final_output['predicted data']
final_output.head()

NameError: name 'pd' is not defined

In [3]:
#the model can be saved as
torch.save(model, 'HousePriceUsingDeepLearning.pt')

#the weights of the model can be saved as
torch.save(model.state_dict(), 'HousePriceUsingDeepLearning.pt')

NameError: name 'torch' is not defined

In [4]:
#now, the saved model can be loaded as

embs_size=[(15, 8), (5,3), (2,1), (4,2)]
model1=FeedForward(embs_size, 5, 1, [100, 50], p=0.5)
model1.load_state_dict(torch.load('HousePriceUsingDeepLearning.pt'))



NameError: name 'FeedForward' is not defined

In [ ]:
model1.eval()
#rerun everything again
#outputs must be the same as while loading the model at class definition 